# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class BankBranchEtl(models.Model):
    department_table_id = models.CharField(max_length=255, blank=True, null=True)
    department = models.CharField(max_length=255, blank=True, null=True)
    schema_or_table_name = models.CharField(max_length=255, blank=True, null=True)
    op_date = models.DateTimeField(blank=True, null=True)
    gid = models.CharField(max_length=255, blank=True, null=True)
    item_no = models.CharField(max_length=255, blank=True, null=True)
    tran_no = models.CharField(max_length=255, blank=True, null=True)
    applicant_name = models.CharField(max_length=255, blank=True, null=True)
    app_type = models.CharField(max_length=255, blank=True, null=True)
    tran_amount = models.CharField(max_length=255, blank=True, null=True)
    app_id = models.CharField(max_length=255, blank=True, null=True)
    tran_date = models.DateTimeField(blank=True, null=True)
    full_rem = models.CharField(max_length=255, blank=True, null=True)
    payment_mode = models.CharField(max_length=255, blank=True, null=True)
    response_code = models.CharField(max_length=255, blank=True, null=True)
    state_code = models.CharField(max_length=255, blank=True, null=True)
    state_name = models.CharField(max_length=255, blank=True, null=True)
    approval_code = models.CharField(max_length=255, blank=True, null=True)
    bank_name = models.CharField(max_length=255, blank=True, null=True)
    bank_code = models.CharField(max_length=255, blank=True, null=True)
    account_name_bank = models.CharField(max_length=255, blank=True, null=True)
    retailer_id = models.CharField(max_length=255, blank=True, null=True)
    term_id = models.CharField(max_length=255, blank=True, null=True)
    tran_currency = models.CharField(max_length=255, blank=True, null=True)
    branch_code = models.CharField(max_length=255, blank=True, null=True)
    payment_status = models.CharField(max_length=255, blank=True, null=True)
    reference_no = models.CharField(max_length=255, blank=True, null=True)
    settled_status = models.CharField(max_length=255, blank=True, null=True)
    deposit_slip_no = models.CharField(max_length=255, blank=True, null=True)
    response = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'bank_branch_etl'


class CardAccountDetailsIssuing(models.Model):
    department_table_id = models.CharField(max_length=255, blank=True, null=True)
    department = models.CharField(max_length=255, blank=True, null=True)
    schema_or_table_name = models.CharField(max_length=255, blank=True, null=True)
    client_id = models.CharField(max_length=255, blank=True, null=True)
    branch = models.FloatField(blank=True, null=True)
    pan = models.CharField(max_length=255, blank=True, null=True)
    account_no = models.CharField(max_length=255, blank=True, null=True)
    card_type = models.CharField(max_length=255, blank=True, null=True)
    tcard_createdate = models.DateTimeField(blank=True, null=True)
    tcard_updatedate = models.DateTimeField(blank=True, null=True)
    tcard_crd_stat = models.CharField(max_length=255, blank=True, null=True)
    tcard_sign_stat = models.IntegerField(blank=True, null=True)
    taccount_stat = models.CharField(max_length=255, blank=True, null=True)
    tcard_orderdate = models.DateTimeField(blank=True, null=True)
    tcard_canceldate = models.DateTimeField(blank=True, null=True)
    tcard_makingdate = models.DateTimeField(blank=True, null=True)
    tcard_distributiondate = models.DateTimeField(blank=True, null=True)
    taccount_closedate = models.DateTimeField(blank=True, null=True)
    taccount_updatedate = models.DateTimeField(blank=True, null=True)
    currency_no = models.CharField(max_length=255, blank=True, null=True)
    insure = models.CharField(max_length=255, blank=True, null=True)
    cvv = models.CharField(max_length=255, blank=True, null=True)
    cvv2 = models.CharField(max_length=255, blank=True, null=True)
    making_priority = models.CharField(max_length=255, blank=True, null=True)
    parent_mbr = models.CharField(max_length=255, blank=True, null=True)
    grp_limit = models.CharField(max_length=255, blank=True, null=True)
    pin_block = models.CharField(max_length=255, blank=True, null=True)
    card_product = models.CharField(max_length=255, blank=True, null=True)
    ipvv = models.CharField(max_length=255, blank=True, null=True)
    name_on_card = models.CharField(max_length=255, blank=True, null=True)
    create_sys_date = models.DateTimeField(blank=True, null=True)
    close_sys_date = models.DateTimeField(blank=True, null=True)
    risk_level = models.CharField(max_length=255, blank=True, null=True)
    remake = models.CharField(max_length=255, blank=True, null=True)
    remark = models.CharField(max_length=255, blank=True, null=True)
    guid = models.CharField(max_length=255, blank=True, null=True)
    contactlesscapable = models.CharField(max_length=255, blank=True, null=True)
    protected_amount = models.CharField(max_length=255, blank=True, null=True)
    existsinpc = models.CharField(max_length=255, blank=True, null=True)
    counter_grpid = models.CharField(max_length=255, blank=True, null=True)
    internal_limits_group_sys_id = models.CharField(max_length=255, blank=True, null=True)
    remain_update_date = models.DateTimeField(blank=True, null=True)
    update_revision = models.CharField(max_length=255, blank=True, null=True)
    limit_grp_id = models.CharField(max_length=255, blank=True, null=True)
    lower_main = models.CharField(max_length=255, blank=True, null=True)
    credit_reserve = models.CharField(max_length=255, blank=True, null=True)
    debit_reserve = models.CharField(max_length=255, blank=True, null=True)
    acct_stat = models.CharField(max_length=255, blank=True, null=True)
    acct_typ = models.CharField(max_length=255, blank=True, null=True)
    update_sys_date = models.DateTimeField(blank=True, null=True)
    update_clerk_code = models.CharField(max_length=255, blank=True, null=True)
    create_clerk_code = models.CharField(max_length=255, blank=True, null=True)
    over_draft = models.CharField(max_length=255, blank=True, null=True)
    available = models.CharField(max_length=255, blank=True, null=True)
    account_type = models.CharField(max_length=255, blank=True, null=True)
    taccount_createdate = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'card_account_details_issuing'


class CardClientPersonnelIssuing(models.Model):
    department_table_id = models.CharField(max_length=255, blank=True, null=True)
    department = models.CharField(max_length=255, blank=True, null=True)
    branch = models.CharField(max_length=255, blank=True, null=True)
    client_id = models.CharField(max_length=255, blank=True, null=True)
    country_res = models.CharField(max_length=255, blank=True, null=True)
    sex = models.CharField(max_length=255, blank=True, null=True)
    birthday = models.DateTimeField(blank=True, null=True)
    birth_place = models.CharField(max_length=255, blank=True, null=True)
    foreign_pass = models.CharField(max_length=255, blank=True, null=True)
    foreign_exp = models.DateTimeField(blank=True, null=True)
    country_reg = models.CharField(max_length=255, blank=True, null=True)
    region_reg = models.CharField(max_length=255, blank=True, null=True)
    city_reg = models.CharField(max_length=255, blank=True, null=True)
    zip_reg = models.CharField(max_length=255, blank=True, null=True)
    address_reg = models.CharField(max_length=255, blank=True, null=True)
    country_live = models.CharField(max_length=255, blank=True, null=True)
    region_live = models.CharField(max_length=255, blank=True, null=True)
    city_live = models.CharField(max_length=255, blank=True, null=True)
    zip_live = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    country_cont = models.CharField(max_length=255, blank=True, null=True)
    region_cont = models.CharField(max_length=255, blank=True, null=True)
    city_cont = models.CharField(max_length=255, blank=True, null=True)
    zip_cont = models.CharField(max_length=255, blank=True, null=True)
    address_cont = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    fax = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    mobile_phone = models.CharField(max_length=255, blank=True, null=True)
    pager = models.CharField(max_length=255, blank=True, null=True)
    company = models.CharField(max_length=255, blank=True, null=True)
    office = models.CharField(max_length=255, blank=True, null=True)
    tab_no = models.CharField(max_length=255, blank=True, null=True)
    job_title = models.CharField(max_length=255, blank=True, null=True)
    job_phone = models.CharField(max_length=255, blank=True, null=True)
    date_create = models.DateTimeField(blank=True, null=True)
    date_modify = models.DateTimeField(blank=True, null=True)
    occupation = models.CharField(max_length=255, blank=True, null=True)
    vip = models.CharField(max_length=255, blank=True, null=True)
    insider = models.CharField(max_length=255, blank=True, null=True)
    resident = models.CharField(max_length=255, blank=True, null=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    street_reg = models.CharField(max_length=255, blank=True, null=True)
    house_reg = models.CharField(max_length=255, blank=True, null=True)
    death_date = models.DateTimeField(blank=True, null=True)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    middle_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    category_id = models.CharField(max_length=255, blank=True, null=True)
    grp_limit = models.CharField(max_length=255, blank=True, null=True)
    grp_limit_int = models.CharField(max_length=255, blank=True, null=True)
    limit_currency = models.CharField(max_length=255, blank=True, null=True)
    schema_or_table_name = models.CharField(max_length=255, blank=True, null=True)
    bankrupt = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'card_client_personnel_issuing'


class CipaPartiesMerchant(models.Model):
    code = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    bank = models.CharField(max_length=255, blank=True, null=True)
    account = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    isenabled = models.CharField(max_length=255, blank=True, null=True)
    ismerchant = models.CharField(max_length=255, blank=True, null=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    profileid = models.CharField(max_length=255, blank=True, null=True)
    feeincluded = models.CharField(max_length=255, blank=True, null=True)
    secretkey = models.CharField(max_length=255, blank=True, null=True)
    ipaddresses = models.CharField(max_length=255, blank=True, null=True)
    merchantid = models.CharField(max_length=255, blank=True, null=True)
    merid = models.CharField(max_length=255, blank=True, null=True)
    profilename = models.CharField(max_length=255, blank=True, null=True)
    terminalid = models.CharField(max_length=255, blank=True, null=True)
    discriminator = models.CharField(max_length=255, blank=True, null=True)
    retailerid = models.CharField(max_length=255, blank=True, null=True)
    migrated = models.CharField(max_length=255, blank=True, null=True)
    amexid = models.CharField(max_length=255, blank=True, null=True)
    iscardenabled = models.CharField(max_length=255, blank=True, null=True)
    isrecurring = models.CharField(max_length=255, blank=True, null=True)
    payattitudefee = models.CharField(max_length=255, blank=True, null=True)
    cardfee = models.CharField(max_length=255, blank=True, null=True)
    maxfee = models.CharField(max_length=255, blank=True, null=True)
    vat = models.CharField(max_length=255, blank=True, null=True)
    addvat = models.CharField(max_length=255, blank=True, null=True)
    encryptionkey = models.CharField(max_length=255, blank=True, null=True)
    encryptioniv = models.CharField(max_length=255, blank=True, null=True)
    reversalenabled = models.CharField(max_length=255, blank=True, null=True)
    enablecardonfile = models.CharField(max_length=255, blank=True, null=True)
    cardonfileref = models.CharField(max_length=255, blank=True, null=True)
    cardonfileid = models.CharField(max_length=255, blank=True, null=True)
    ordertimeout = models.CharField(max_length=255, blank=True, null=True)
    disablepayattitude = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'cipa_parties_merchant'


class Holdertags(models.Model):
    department = models.TextField(blank=True, null=True)
    schema_type = models.TextField(blank=True, null=True)
    phone = models.TextField(blank=True, null=True)
    holderid = models.TextField(blank=True, null=True)
    isactive = models.TextField(blank=True, null=True)
    isprepaid = models.TextField(blank=True, null=True)
    prepaidaccountid = models.TextField(blank=True, null=True)
    isdebit = models.TextField(blank=True, null=True)
    bankaccount = models.TextField(blank=True, null=True)
    pin = models.TextField(blank=True, null=True)
    pinstreak = models.TextField(blank=True, null=True)
    status = models.TextField(blank=True, null=True)
    created = models.TextField(blank=True, null=True)
    branch = models.TextField(blank=True, null=True)
    onlineprofile = models.TextField(blank=True, null=True)
    offlineprofile = models.TextField(blank=True, null=True)
    institution = models.TextField(blank=True, null=True)
    agentid = models.TextField(blank=True, null=True)
    ispremium = models.TextField(blank=True, null=True)
    recurringsubscriptionfee = models.TextField(blank=True, null=True)
    tagstatus = models.TextField(blank=True, null=True)
    activationdate = models.TextField(blank=True, null=True)
    lastpaymentdate = models.TextField(blank=True, null=True)
    nextpaymentdate = models.TextField(blank=True, null=True)
    subtype = models.TextField(blank=True, null=True)
    subscriptiontransactionid = models.TextField(blank=True, null=True)
    activationtransactionid = models.TextField(blank=True, null=True)
    nickname = models.TextField(blank=True, null=True)
    isverified1 = models.TextField(blank=True, null=True)
    verificationaccesstime = models.TextField(blank=True, null=True)
    verificationcomment = models.TextField(blank=True, null=True)
    selectcount = models.TextField(blank=True, null=True)
    verifier = models.TextField(blank=True, null=True)
    isverified = models.TextField(blank=True, null=True)
    agentcode = models.TextField(blank=True, null=True)
    pendforadditionalaccount = models.TextField(blank=True, null=True)
    isdefault = models.TextField(blank=True, null=True)
    channel = models.TextField(blank=True, null=True)
    recomputed = models.TextField(blank=True, null=True)
    email = models.TextField(blank=True, null=True)
    firstname = models.TextField(blank=True, null=True)
    lastname = models.TextField(blank=True, null=True)
    middlename = models.TextField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    city = models.TextField(blank=True, null=True)
    state = models.TextField(blank=True, null=True)
    nationality = models.TextField(blank=True, null=True)
    sex = models.TextField(blank=True, null=True)
    marriage = models.TextField(blank=True, null=True)
    profession = models.TextField(blank=True, null=True)
    occupation = models.TextField(blank=True, null=True)
    bvn = models.TextField(blank=True, null=True)
    birthday = models.TextField(blank=True, null=True)
    premiumactivated = models.TextField(blank=True, null=True)
    accountid = models.TextField(blank=True, null=True)
    isagent = models.TextField(blank=True, null=True)
    isverified2 = models.TextField(blank=True, null=True)
    nin = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'holdertags'


class PayarenaExchange(models.Model):
    department_table_id = models.CharField(max_length=255, blank=True, null=True)
    department = models.CharField(max_length=255, blank=True, null=True)
    schema_or_table_name = models.CharField(max_length=255, blank=True, null=True)
    request_time = models.DateTimeField(blank=True, null=True)
    response_time = models.DateTimeField(blank=True, null=True)
    account_no = models.CharField(max_length=255, blank=True, null=True)
    amount = models.CharField(max_length=255, blank=True, null=True)
    request_id = models.CharField(max_length=255, blank=True, null=True)
    request_type = models.CharField(max_length=255, blank=True, null=True)
    route = models.CharField(max_length=255, blank=True, null=True)
    status_code = models.CharField(max_length=255, blank=True, null=True)
    status_message = models.CharField(max_length=255, blank=True, null=True)
    response_id = models.CharField(max_length=255, blank=True, null=True)
    rrn = models.CharField(max_length=255, blank=True, null=True)
    client = models.CharField(max_length=255, blank=True, null=True)
    reversed = models.CharField(max_length=255, blank=True, null=True)
    reversible = models.CharField(max_length=255, blank=True, null=True)
    batch_id = models.CharField(max_length=255, blank=True, null=True)
    beneficiary = models.CharField(max_length=255, blank=True, null=True)
    sender = models.CharField(max_length=255, blank=True, null=True)
    reference = models.CharField(max_length=255, blank=True, null=True)
    channel = models.CharField(max_length=255, blank=True, null=True)
    source_bank = models.CharField(max_length=255, blank=True, null=True)
    txid = models.CharField(max_length=255, blank=True, null=True)
    dest_bank = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'payarena_exchange'


class ProcessRecord(models.Model):
    script_name = models.TextField(blank=True, null=True)
    record = models.IntegerField(blank=True, null=True)
    last_date_ran = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'process_record'


class SettlementDetail(models.Model):
    id_field = models.AutoField(db_column='id_', primary_key=True)  # Field renamed because it ended with '_'.
    department_table_id = models.CharField(blank=True, null=True)
    department = models.CharField(blank=True, null=True)
    ptsa_bank = models.CharField(blank=True, null=True)
    unsharedmsc1_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    ptsa_code = models.CharField(blank=True, null=True)
    pros_account = models.CharField(blank=True, null=True)
    terw_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    sharingmsc1_diffrate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    merchantdepositbankcode2 = models.CharField(blank=True, null=True)
    process_status = models.CharField(blank=True, null=True)
    merchantdepositbankcode = models.CharField(blank=True, null=True)
    remark = models.CharField(blank=True, null=True)
    ptsa_account = models.CharField(blank=True, null=True)
    cpd = models.DateField(blank=True, null=True)
    serviceprovider = models.CharField(blank=True, null=True)
    swth_name = models.CharField(blank=True, null=True)
    acqrvat = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    agnt_code = models.CharField(blank=True, null=True)
    swth_bankcode = models.CharField(blank=True, null=True)
    bilr_name = models.CharField(blank=True, null=True)
    bilr_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    terw_bankcode = models.CharField(blank=True, null=True)
    exchangerate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    revw_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    uphss_transref = models.CharField(blank=True, null=True)
    settlementaccount3 = models.CharField(blank=True, null=True)
    superagentrate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    agnt_bankcode = models.CharField(blank=True, null=True)
    swth_account = models.CharField(blank=True, null=True)
    msc2_amount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    outboundnonbankfee = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    vend_code = models.CharField(blank=True, null=True)
    sign = models.CharField(blank=True, null=True)
    sharingmsc1_amount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    userdata = models.CharField(blank=True, null=True)
    vast_bank = models.CharField(blank=True, null=True)
    customerid = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    merchantdepositbank4 = models.CharField(blank=True, null=True)
    beneficiarybank = models.CharField(blank=True, null=True)
    blrr_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    fullrem_translation = models.CharField(blank=True, null=True)
    proc_bank = models.CharField(blank=True, null=True)
    phoneno = models.CharField(blank=True, null=True)
    transtime = models.CharField(blank=True, null=True)
    ptsp_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    vend_bankcode = models.CharField(blank=True, null=True)
    acqr_name = models.CharField(blank=True, null=True)
    pros_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    revenuecode = models.CharField(blank=True, null=True)
    host = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    standard_cap = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    specialcard_owner = models.CharField(blank=True, null=True)
    terw_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    total_msc = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    revw_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    merchantdepositbank2 = models.CharField(blank=True, null=True)
    sdsubscalbasis = models.CharField(blank=True, null=True)
    issr_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    vend_account = models.CharField(blank=True, null=True)
    effective_sharingamount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    blrr_account = models.CharField(blank=True, null=True)
    net_amountduemerchant5 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    uprate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    govt_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    mbr = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    msc1_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    merchantdepositbankcode5 = models.CharField(blank=True, null=True)
    vast_name = models.CharField(blank=True, null=True)
    stampdutycharge = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    merchantdepositbankcode4 = models.CharField(blank=True, null=True)
    bllr_name = models.CharField(blank=True, null=True)
    settlementaccount = models.CharField(blank=True, null=True)
    coaq_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    standard_msc = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    pros_bankcode = models.CharField(blank=True, null=True)
    tech_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    vatcalbasis = models.CharField(blank=True, null=True)
    pros_code = models.CharField(blank=True, null=True)
    agnt_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    merchantname = models.CharField(blank=True, null=True)
    issr_bank = models.CharField(blank=True, null=True)
    sectorcode = models.CharField(blank=True, null=True)
    vend_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    debitval = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    specialcard = models.CharField(blank=True, null=True)
    origid = models.CharField(blank=True, null=True)
    vatcharge = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    issr_name = models.CharField(blank=True, null=True)
    perchantage4 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    iss_stan = models.CharField(blank=True, null=True)
    settlementcurrency = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    invoicenum = models.CharField(blank=True, null=True)
    settlementaccount4 = models.CharField(blank=True, null=True)
    blrr_name = models.CharField(blank=True, null=True)
    proc_bankcode = models.CharField(blank=True, null=True)
    swth_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    effectivemsc = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    bilr_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    agnt_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    amountorigdcc = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    blrr_code = models.CharField(blank=True, null=True)
    bilr_account = models.CharField(blank=True, null=True)
    msc_amount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    tranxsaved = models.CharField(blank=True, null=True)
    cardcountry = models.CharField(blank=True, null=True)
    tlocation = models.CharField(blank=True, null=True)
    ptsp_account = models.CharField(blank=True, null=True)
    merchantdepositbank6 = models.CharField(blank=True, null=True)
    acquirer = models.CharField(blank=True, null=True)
    pros_name = models.CharField(blank=True, null=True)
    reportdate = models.DateField(blank=True, null=True)
    reporttype = models.CharField(blank=True, null=True)
    ptsa_name = models.CharField(blank=True, null=True)
    perc_allotmerchant = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    perchantage3 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    perchantage5 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    term = models.CharField(blank=True, null=True)
    acqstan = models.CharField(blank=True, null=True)
    approval = models.CharField(blank=True, null=True)
    issuer = models.CharField(blank=True, null=True)
    terwvat = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    beneficiaryaccountno = models.CharField(blank=True, null=True)
    vend_bank = models.CharField(blank=True, null=True)
    isscountry = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    perchantage6 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    extrrn = models.CharField(blank=True, null=True)
    swthvat = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    servicetype = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    ptsp_bank = models.CharField(blank=True, null=True)
    sharingmsc1_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    ptspvat = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    qocfee = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    bllr_bankcode = models.CharField(blank=True, null=True)
    issrvat = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    procvat = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    msc2_splitsharing = models.CharField(blank=True, null=True)
    superagentacct = models.CharField(blank=True, null=True)
    fcyamount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    sharingmsc1_diffamount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    terminstid = models.CharField(blank=True, null=True)
    batchno = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    ptsp_code = models.CharField(blank=True, null=True)
    recordid = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    msc1_cap = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    merchantdepositbank1 = models.CharField(blank=True, null=True)
    coaq_name = models.CharField(blank=True, null=True)
    seqnum = models.CharField(blank=True, null=True)
    currencyorigdcc = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    acqr_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    fee2 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    sdsubsvalue = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    govt_name = models.CharField(blank=True, null=True)
    docno = models.CharField(blank=True, null=True)
    subsidy_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    blrr_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    vast_account = models.CharField(blank=True, null=True)
    tranamount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    opdate = models.DateField(blank=True, null=True)
    processingfee = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    issr_bankcode = models.CharField(blank=True, null=True)
    bifee = models.CharField(blank=True, null=True)
    createdate = models.DateField(blank=True, null=True)
    creditval = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    serviceprovideraccountno = models.CharField(blank=True, null=True)
    bllr_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    time = models.DateField(blank=True, null=True)
    msc1_amount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    net_amountduemerchant2 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    sector = models.CharField(blank=True, null=True)
    govt_account = models.CharField(blank=True, null=True)
    msc2_cap = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    coaq_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    pan = models.CharField(blank=True, null=True)
    merchantdepositbank = models.CharField(blank=True, null=True)
    meb_batchno = models.CharField(blank=True, null=True)
    mscconcession_amount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    mcc = models.CharField(blank=True, null=True)
    irf = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    swth_code = models.CharField(blank=True, null=True)
    merchantoutletname = models.CharField(blank=True, null=True)
    acqfiid = models.CharField(blank=True, null=True)
    mcc_description = models.CharField(blank=True, null=True)
    stan = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    ptsp_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    docno_tem = models.CharField(blank=True, null=True)
    superagentvalue = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    opdate2 = models.DateField(blank=True, null=True)
    beneficiaryname = models.CharField(blank=True, null=True)
    blrr_bank = models.CharField(blank=True, null=True)
    blrr_bankcode = models.CharField(blank=True, null=True)
    agnt_name = models.CharField(blank=True, null=True)
    net_amountduemerchant3 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    totalagentfee = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    irf_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    govt_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    textmess = models.CharField(blank=True, null=True)
    settlementaccount6 = models.CharField(blank=True, null=True)
    unsharedmsc1_amount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    carf = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    perc_allotupsl = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    trannumber = models.CharField(blank=True, null=True)
    vend_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    reversereqid = models.CharField(blank=True, null=True)
    settlementdate_prev = models.DateField(blank=True, null=True)
    trandate = models.DateField(blank=True, null=True)
    merchantdepositbankcode3 = models.CharField(blank=True, null=True)
    msc2_splitsharingacct = models.CharField(blank=True, null=True)
    acqcountry = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    settlementaccount2 = models.CharField(blank=True, null=True)
    vast_code = models.CharField(blank=True, null=True)
    acqr_bank = models.CharField(blank=True, null=True)
    vast_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    coaq_account = models.CharField(blank=True, null=True)
    fee1 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    mscconcession_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    terw_bank = models.CharField(blank=True, null=True)
    tech_name = models.CharField(blank=True, null=True)
    maskedpan = models.CharField(blank=True, null=True)
    vast_bankcode = models.CharField(blank=True, null=True)
    bllr_account = models.CharField(blank=True, null=True)
    merchantdepositbankcode6 = models.CharField(blank=True, null=True)
    margin = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    settlementdate = models.DateField(blank=True, null=True)
    issr_account = models.CharField(blank=True, null=True)
    traceno = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    issr_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    revw_name = models.CharField(blank=True, null=True)
    agnt_account = models.CharField(blank=True, null=True)
    creditacct = models.CharField(blank=True, null=True)
    amountdue_issuer = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    pros_bank = models.CharField(blank=True, null=True)
    merchantid = models.CharField(blank=True, null=True)
    beneficiarybankcode = models.CharField(blank=True, null=True)
    acqr_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    ptsp_name = models.CharField(blank=True, null=True)
    meb_issfiid = models.CharField(blank=True, null=True)
    fullrem = models.CharField(blank=True, null=True)
    issfiid = models.CharField(blank=True, null=True)
    total_amountdue = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    bllr_code = models.CharField(blank=True, null=True)
    ptsavat = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    terw_code = models.CharField(blank=True, null=True)
    pros_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    msc2_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    merchantdepositbankcode1 = models.CharField(blank=True, null=True)
    perchantage1 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    net_amountduemerchant6 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    vast_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    ptsa_value = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    net_amountduemerchant = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    origtype = models.CharField(blank=True, null=True)
    perchantage2 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    merchantdepositbank5 = models.CharField(blank=True, null=True)
    merchantdepositbank3 = models.CharField(blank=True, null=True)
    extpaymentfields = models.CharField(blank=True, null=True)
    ptsa_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    terw_name = models.CharField(blank=True, null=True)
    tech_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    debitacct = models.CharField(blank=True, null=True)
    serviceproviderbankcode = models.CharField(blank=True, null=True)
    id = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    superagentacctname = models.CharField(blank=True, null=True)
    agnt_bank = models.CharField(blank=True, null=True)
    expdate = models.DateField(blank=True, null=True)
    cleanupflag = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    acqr_account = models.CharField(blank=True, null=True)
    deduction_amountdue = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    marginvat = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    settlementaccount1 = models.CharField(blank=True, null=True)
    merchantdepositbankacctno = models.CharField(blank=True, null=True)
    perc_allotothers = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    customeraccount = models.CharField(blank=True, null=True)
    cardscheme = models.CharField(blank=True, null=True)
    terw_account = models.CharField(blank=True, null=True)
    subsidy_amount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    settlementamount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    swth_rate = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    serviceproviderbank = models.CharField(blank=True, null=True)
    acqr_bankcode = models.CharField(blank=True, null=True)
    tech_account = models.CharField(blank=True, null=True)
    acquirer_ref = models.CharField(blank=True, null=True)
    settlementaccount5 = models.CharField(blank=True, null=True)
    old_textmess = models.CharField(blank=True, null=True)
    swth_bank = models.CharField(blank=True, null=True)
    ptsp_bankcode = models.CharField(blank=True, null=True)
    net_amountduemerchant1 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    vend_name = models.CharField(blank=True, null=True)
    net_amountduemerchant4 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    originalamount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    fio = models.CharField(blank=True, null=True)
    trancur = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    ptsa_bankcode = models.CharField(blank=True, null=True)
    settlement_service = models.CharField(blank=True, null=True)
    toacct2 = models.CharField(blank=True, null=True)
    reportflag = models.CharField(max_length=1, blank=True, null=True)
    lcyamount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    revw_account = models.CharField(blank=True, null=True)
    bllr_bank = models.CharField(blank=True, null=True)
    reasonforalteration = models.CharField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'settlement_detail'


class SettlementMeb(models.Model):
    department_table_id = models.CharField(max_length=1255, blank=True, null=True)
    department = models.CharField(max_length=1255, blank=True, null=True)
    opdate = models.DateTimeField(blank=True, null=True)
    clerkcode = models.CharField(max_length=1255, blank=True, null=True)
    station = models.CharField(max_length=1255, blank=True, null=True)
    docno = models.CharField(max_length=1255, blank=True, null=True)
    no = models.CharField(max_length=1255, blank=True, null=True)
    entcode = models.CharField(max_length=1255, blank=True, null=True)
    debitacct = models.CharField(max_length=1255, blank=True, null=True)
    debitval = models.CharField(max_length=1255, blank=True, null=True)
    creditacct = models.CharField(max_length=1255, blank=True, null=True)
    creditval = models.CharField(max_length=1255, blank=True, null=True)
    shortrem = models.CharField(max_length=1255, blank=True, null=True)
    fullrem = models.CharField(max_length=1255, blank=True, null=True)
    device = models.CharField(max_length=1255, blank=True, null=True)
    extentcode = models.CharField(max_length=1255, blank=True, null=True)
    trandate = models.CharField(max_length=1255, blank=True, null=True)
    issficode = models.CharField(max_length=1255, blank=True, null=True)
    issfiid = models.CharField(max_length=1255, blank=True, null=True)
    issps = models.CharField(max_length=1225, blank=True, null=True)
    isscountry = models.CharField(max_length=1255, blank=True, null=True)
    pan = models.CharField(max_length=1255, blank=True, null=True)
    mbr = models.CharField(max_length=1255, blank=True, null=True)
    expdate = models.DateTimeField(blank=True, null=True)
    approval = models.CharField(max_length=1255, blank=True, null=True)
    acqficode = models.CharField(max_length=1255, blank=True, null=True)
    acqfiid = models.CharField(max_length=1255, blank=True, null=True)
    acqps = models.CharField(max_length=1255, blank=True, null=True)
    acqcountry = models.CharField(max_length=1255, blank=True, null=True)
    termcode = models.CharField(max_length=1255, blank=True, null=True)
    term = models.CharField(max_length=1255, blank=True, null=True)
    retailer = models.CharField(max_length=1255, blank=True, null=True)
    tlocation = models.CharField(max_length=1255, blank=True, null=True)
    mcc = models.CharField(max_length=1255, blank=True, null=True)
    stan = models.CharField(max_length=1255, blank=True, null=True)
    acqiin = models.CharField(max_length=1255, blank=True, null=True)
    forwardiin = models.CharField(max_length=1255, blank=True, null=True)
    invoice = models.CharField(max_length=1255, blank=True, null=True)
    userdata = models.CharField(max_length=1255, blank=True, null=True)
    tranamount = models.CharField(max_length=1255, blank=True, null=True)
    trancur = models.CharField(max_length=1255, blank=True, null=True)
    orgamount = models.CharField(max_length=1255, blank=True, null=True)
    orgcur = models.CharField(max_length=1255, blank=True, null=True)
    acqfee = models.CharField(max_length=1255, blank=True, null=True)
    acqfeecur = models.CharField(max_length=1255, blank=True, null=True)
    issfee = models.CharField(max_length=1255, blank=True, null=True)
    issfeecur = models.CharField(max_length=1255, blank=True, null=True)
    intrfee = models.CharField(max_length=1255, blank=True, null=True)
    intrfeecur = models.CharField(max_length=1255, blank=True, null=True)
    ident1 = models.CharField(max_length=1255, blank=True, null=True)
    info1 = models.CharField(max_length=1255, blank=True, null=True)
    ident2 = models.CharField(max_length=1255, blank=True, null=True)
    info2 = models.CharField(max_length=1255, blank=True, null=True)
    ident3 = models.CharField(max_length=1255, blank=True, null=True)
    info3 = models.CharField(max_length=1255, blank=True, null=True)
    debitcur = models.CharField(max_length=1255, blank=True, null=True)
    creditcur = models.CharField(max_length=1255, blank=True, null=True)
    crnum = models.CharField(max_length=1255, blank=True, null=True)
    bifee = models.CharField(max_length=1255, blank=True, null=True)
    usdfn = models.CharField(max_length=1255, blank=True, null=True)
    usdfn2 = models.CharField(max_length=1255, blank=True, null=True)
    usdfn3 = models.CharField(max_length=1255, blank=True, null=True)
    process_status = models.CharField(max_length=1255, blank=True, null=True)
    remark = models.CharField(max_length=1255, blank=True, null=True)
    recordid = models.CharField(max_length=1255, blank=True, null=True)
    transign = models.CharField(max_length=1255, blank=True, null=True)
    batchno = models.CharField(max_length=1255, blank=True, null=True)
    code = models.CharField(max_length=1255, blank=True, null=True)
    opdate2 = models.DateTimeField(blank=True, null=True)
    createdate = models.DateTimeField(blank=True, null=True)
    info1_temp = models.CharField(max_length=1255, blank=True, null=True)
    scheme = models.CharField(max_length=1255, blank=True, null=True)
    docno_temp = models.CharField(max_length=1255, blank=True, null=True)
    generatedflag = models.CharField(max_length=1255, blank=True, null=True)
    packno = models.CharField(max_length=1255, blank=True, null=True)
    trannumber = models.CharField(max_length=1255, blank=True, null=True)
    type = models.CharField(max_length=1255, blank=True, null=True)
    origtype = models.CharField(max_length=1255, blank=True, null=True)
    origid = models.CharField(max_length=1255, blank=True, null=True)
    origunit = models.CharField(max_length=1255, blank=True, null=True)
    host = models.CharField(max_length=1255, blank=True, null=True)
    hostinterface = models.CharField(max_length=1255, blank=True, null=True)
    time = models.DateTimeField(blank=True, null=True)
    origtime = models.DateTimeField(blank=True, null=True)
    phase = models.CharField(max_length=1255, blank=True, null=True)
    termclass = models.CharField(max_length=1255, blank=True, null=True)
    termname = models.CharField(max_length=1255, blank=True, null=True)
    termname2 = models.CharField(max_length=1255, blank=True, null=True)
    termdate = models.DateTimeField(blank=True, null=True)
    termpsname = models.CharField(max_length=1255, blank=True, null=True)
    termfiid = models.CharField(max_length=1255, blank=True, null=True)
    termfiname = models.CharField(max_length=1255, blank=True, null=True)
    terminstid = models.CharField(max_length=1255, blank=True, null=True)
    termretailer = models.CharField(max_length=1255, blank=True, null=True)
    termretailername = models.CharField(max_length=1255, blank=True, null=True)
    termsic = models.CharField(max_length=1255, blank=True, null=True)
    terminstcountry = models.CharField(max_length=1255, blank=True, null=True)
    termcountry = models.CharField(max_length=1255, blank=True, null=True)
    termcounty = models.CharField(max_length=1255, blank=True, null=True)
    termstate = models.CharField(max_length=1255, blank=True, null=True)
    termregion = models.CharField(max_length=1255, blank=True, null=True)
    termcity = models.CharField(max_length=1255, blank=True, null=True)
    termzip = models.CharField(max_length=1255, blank=True, null=True)
    termlocation = models.CharField(max_length=1255, blank=True, null=True)
    termdescription = models.CharField(max_length=1255, blank=True, null=True)
    termbranch = models.CharField(max_length=1255, blank=True, null=True)
    termowner = models.CharField(max_length=1255, blank=True, null=True)
    termtimeoffset = models.CharField(max_length=1255, blank=True, null=True)
    termapprvcodelen = models.CharField(max_length=1255, blank=True, null=True)
    termentrycaps = models.CharField(max_length=1255, blank=True, null=True)
    authfiid = models.CharField(max_length=1255, blank=True, null=True)
    authfiname = models.CharField(max_length=1255, blank=True, null=True)
    authpsname = models.CharField(max_length=1255, blank=True, null=True)
    sponsorfiid = models.CharField(max_length=1255, blank=True, null=True)
    trancode = models.CharField(max_length=1255, blank=True, null=True)
    trancategory = models.CharField(max_length=1255, blank=True, null=True)
    draftcapture = models.CharField(max_length=1255, blank=True, null=True)
    fromaccttype = models.CharField(max_length=1255, blank=True, null=True)
    fromacct = models.CharField(max_length=1255, blank=True, null=True)
    fromacctdescr = models.CharField(max_length=1255, blank=True, null=True)
    toaccttype = models.CharField(max_length=1255, blank=True, null=True)
    toacct = models.CharField(max_length=1255, blank=True, null=True)
    toacctdescr = models.CharField(max_length=1255, blank=True, null=True)
    toacct2 = models.CharField(max_length=1255, blank=True, null=True)
    correspacct = models.CharField(max_length=1255, blank=True, null=True)
    correspamount = models.CharField(max_length=1255, blank=True, null=True)
    fromdate = models.DateTimeField(blank=True, null=True)
    todate = models.DateTimeField(blank=True, null=True)
    amount = models.CharField(max_length=1255, blank=True, null=True)
    amount2 = models.CharField(max_length=1255, blank=True, null=True)
    fee = models.CharField(max_length=1255, blank=True, null=True)
    issuerfee = models.CharField(max_length=1255, blank=True, null=True)
    currency = models.CharField(max_length=1255, blank=True, null=True)
    message = models.CharField(max_length=1255, blank=True, null=True)
    cardmember = models.CharField(max_length=1255, blank=True, null=True)
    pan2 = models.CharField(max_length=1255, blank=True, null=True)
    cardmember2 = models.CharField(max_length=1255, blank=True, null=True)
    authpan = models.CharField(max_length=1255, blank=True, null=True)
    authmbr = models.CharField(max_length=1255, blank=True, null=True)
    prefix = models.CharField(max_length=1255, blank=True, null=True)
    cardprofile = models.CharField(max_length=1255, blank=True, null=True)
    acqgroup = models.CharField(max_length=1255, blank=True, null=True)
    pin = models.CharField(max_length=1255, blank=True, null=True)
    invoicenum = models.CharField(max_length=1255, blank=True, null=True)
    originalinvoicenum = models.CharField(max_length=1255, blank=True, null=True)
    seqnum = models.CharField(max_length=1255, blank=True, null=True)
    originalseqnum = models.CharField(max_length=1255, blank=True, null=True)
    poscondition = models.CharField(max_length=1255, blank=True, null=True)
    respcode = models.CharField(max_length=1255, blank=True, null=True)
    declinereason = models.CharField(max_length=1255, blank=True, null=True)
    responsecondition = models.CharField(max_length=1255, blank=True, null=True)
    approvalcode = models.CharField(max_length=1255, blank=True, null=True)
    textmess = models.CharField(max_length=1255, blank=True, null=True)
    extrrn = models.CharField(max_length=1255, blank=True, null=True)
    extstan = models.CharField(max_length=1255, blank=True, null=True)
    issuercountry = models.CharField(max_length=1255, blank=True, null=True)
    irf = models.CharField(max_length=1255, blank=True, null=True)
    incstan = models.CharField(max_length=1255, blank=True, null=True)
    fep_stan = models.CharField(max_length=1255, blank=True, null=True)
    extpaymentfields = models.CharField(max_length=4000, blank=True, null=True)
    revenuecode = models.CharField(max_length=1255, blank=True, null=True)
    revrequestid = models.CharField(max_length=1255, blank=True, null=True)
    preprocessstatus = models.CharField(max_length=1255, blank=True, null=True)
    posentrymode = models.CharField(max_length=1255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'settlement_meb'


class TransactionType(models.Model):
    bespoke_name = models.TextField(blank=True, null=True)
    bespoke_code = models.TextField(blank=True, null=True)
    processing_code = models.BigIntegerField(blank=True, null=True)
    processing_name = models.TextField(blank=True, null=True)
    processing_constant_name = models.TextField(blank=True, null=True)
    processing_class = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'transaction_type'


class Transactions(models.Model):
    department_table_id = models.CharField(max_length=255, blank=True, null=True)
    department = models.CharField(max_length=255, blank=True, null=True)
    transaction_type = models.CharField(max_length=255, blank=True, null=True)
    transaction_time = models.DateTimeField(blank=True, null=True)
    original_time = models.DateTimeField(blank=True, null=True)
    channel = models.CharField(max_length=255, blank=True, null=True)
    secondary_channel = models.CharField(max_length=255, blank=True, null=True)
    aquirer_terminal_id = models.CharField(max_length=1255, blank=True, null=True)
    acquirer_ps_name = models.CharField(max_length=1255, blank=True, null=True)
    acquirer_institution_id = models.CharField(max_length=1255, blank=True, null=True)
    beneficiary_bank = models.CharField(max_length=1255, blank=True, null=True)
    beneficiary_name = models.CharField(max_length=1255, blank=True, null=True)
    acquirer_country = models.CharField(max_length=1255, blank=True, null=True)
    acquirer_term_state = models.CharField(max_length=1255, blank=True, null=True)
    acquirer_term_city = models.CharField(max_length=1255, blank=True, null=True)
    term_owner = models.CharField(max_length=1255, blank=True, null=True)
    term_entry_caps = models.CharField(max_length=1255, blank=True, null=True)
    from_account = models.CharField(max_length=1255, blank=True, null=True)
    to_account = models.CharField(max_length=1255, blank=True, null=True)
    to_date_field = models.DateTimeField(blank=True, null=True)
    from_date = models.DateTimeField(blank=True, null=True)
    pan = models.CharField(max_length=1255, blank=True, null=True)
    bonus = models.CharField(max_length=1255, blank=True, null=True)
    currency = models.CharField(max_length=1255, blank=True, null=True)
    error = models.CharField(max_length=1255, blank=True, null=True)
    proc_duration = models.CharField(max_length=1255, blank=True, null=True)
    account_id = models.CharField(max_length=1255, blank=True, null=True)
    phone = models.CharField(max_length=1255, blank=True, null=True)
    bank = models.CharField(max_length=1255, blank=True, null=True)
    trx_type = models.CharField(max_length=1255, blank=True, null=True)
    terminal_id = models.CharField(max_length=1255, blank=True, null=True)
    tag = models.CharField(max_length=1255, blank=True, null=True)
    auth_duration = models.CharField(max_length=1255, blank=True, null=True)
    transaction_number = models.CharField(max_length=1255, blank=True, null=True)
    rrn = models.CharField(max_length=1255, blank=True, null=True)
    issuer_country = models.CharField(max_length=1255, blank=True, null=True)
    issuer_institution_id = models.CharField(max_length=1255, blank=True, null=True)
    card_type = models.CharField(max_length=1255, blank=True, null=True)
    issuer_institution_name = models.CharField(max_length=1255, blank=True, null=True)
    account_curreny = models.CharField(max_length=1255, blank=True, null=True)
    curreny_orig = models.CharField(max_length=1255, blank=True, null=True)
    amount = models.FloatField(blank=True, null=True)
    transaction_status = models.CharField(max_length=1255, blank=True, null=True)
    status = models.CharField(max_length=1255, blank=True, null=True)
    status_code = models.CharField(max_length=1255, blank=True, null=True)
    tran_category = models.CharField(max_length=1255, blank=True, null=True)
    merchant_id = models.CharField(max_length=1255, blank=True, null=True)
    terminal_retailer = models.CharField(max_length=1255, blank=True, null=True)
    auth_ps_name = models.CharField(max_length=1255, blank=True, null=True)
    pos_entry_mode = models.CharField(max_length=1255, blank=True, null=True)
    description = models.CharField(max_length=1255, blank=True, null=True)
    stan = models.CharField(max_length=1255, blank=True, null=True)
    fee = models.FloatField(blank=True, null=True)
    total_amount = models.FloatField(blank=True, null=True)
    merchant_fee = models.FloatField(blank=True, null=True)
    merchant_account = models.CharField(max_length=1255, blank=True, null=True)
    direction = models.CharField(max_length=1255, blank=True, null=True)
    authorization_ref = models.CharField(max_length=1255, blank=True, null=True)
    completed = models.CharField(max_length=1255, blank=True, null=True)
    narration = models.CharField(max_length=1255, blank=True, null=True)
    beneficiary = models.CharField(max_length=1255, blank=True, null=True)
    sender_name = models.CharField(max_length=1255, blank=True, null=True)
    sender_bank = models.CharField(max_length=1255, blank=True, null=True)
    sender_account = models.CharField(max_length=1255, blank=True, null=True)
    is_offline = models.CharField(max_length=1255, blank=True, null=True)
    issuer = models.CharField(max_length=1255, blank=True, null=True)
    acquirer = models.CharField(max_length=1255, blank=True, null=True)
    location_field = models.CharField(max_length=1255, blank=True, null=True)
    reversal_transaction_id = models.CharField(max_length=1255, blank=True, null=True)
    request_id = models.CharField(max_length=1255, blank=True, null=True)
    actual_date = models.DateTimeField(blank=True, null=True)
    reversal_date = models.DateTimeField(blank=True, null=True)
    is_reversal = models.CharField(max_length=1255, blank=True, null=True)
    reversed_transaction_id = models.CharField(max_length=1255, blank=True, null=True)
    reversal_reason = models.CharField(max_length=1255, blank=True, null=True)
    proc_code = models.CharField(max_length=1255, blank=True, null=True)
    product_code = models.CharField(max_length=1255, blank=True, null=True)
    accesslog_id = models.CharField(max_length=1255, blank=True, null=True)
    mcc = models.CharField(max_length=1255, blank=True, null=True)
    terminal_date = models.DateTimeField(blank=True, null=True)
    agent = models.CharField(max_length=1255, blank=True, null=True)
    balance = models.CharField(max_length=1255, blank=True, null=True)
    ip = models.CharField(max_length=1255, blank=True, null=True)
    beneficiary_uan = models.CharField(max_length=1255, blank=True, null=True)
    reference_trx_id = models.CharField(max_length=1255, blank=True, null=True)
    holder_id = models.CharField(max_length=1255, blank=True, null=True)
    is_payment_request = models.CharField(max_length=1255, blank=True, null=True)
    receipt = models.CharField(max_length=1255, blank=True, null=True)
    depositor = models.CharField(max_length=1255, blank=True, null=True)
    super_agent_commission = models.CharField(max_length=1255, blank=True, null=True)
    sub_agent_commission = models.CharField(max_length=1255, blank=True, null=True)
    agent_id = models.CharField(max_length=1255, blank=True, null=True)
    agent_code = models.CharField(max_length=1255, blank=True, null=True)
    super_agent_code = models.CharField(max_length=1255, blank=True, null=True)
    debit_code = models.CharField(max_length=1255, blank=True, null=True)
    credit_code = models.CharField(max_length=1255, blank=True, null=True)
    credit_route = models.CharField(max_length=1255, blank=True, null=True)
    issuer_fee = models.FloatField(blank=True, null=True)
    debit_route = models.CharField(max_length=1255, blank=True, null=True)
    ussd_fee = models.FloatField(blank=True, null=True)
    ussd_network = models.CharField(max_length=1255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'transactions'


class UpConTerminalConfig(models.Model):
    department_table_id = models.CharField(max_length=255, blank=True, null=True)
    department = models.CharField(max_length=255, blank=True, null=True)
    schema_or_table_name = models.CharField(max_length=255, blank=True, null=True)
    tid = models.CharField(max_length=255, blank=True, null=True)
    mid = models.CharField(max_length=255, blank=True, null=True)
    serial_number = models.CharField(max_length=255, blank=True, null=True)
    contact_title = models.CharField(max_length=255, blank=True, null=True)
    contact_name = models.CharField(max_length=255, blank=True, null=True)
    init_application_version = models.CharField(max_length=255, blank=True, null=True)
    merchant_name = models.CharField(max_length=255, blank=True, null=True)
    profile_name = models.CharField(max_length=255, blank=True, null=True)
    merchant_address = models.CharField(max_length=255, blank=True, null=True)
    contact_phone = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    state_code = models.CharField(max_length=255, blank=True, null=True)
    date_created = models.CharField(max_length=255, blank=True, null=True)
    bank_accno = models.CharField(max_length=255, blank=True, null=True)
    lga = models.CharField(max_length=255, blank=True, null=True)
    app_name = models.CharField(max_length=255, blank=True, null=True)
    terminal_owner_code = models.CharField(max_length=255, blank=True, null=True)
    terminal_manufacturer = models.CharField(max_length=255, blank=True, null=True)
    terminal_model = models.CharField(max_length=255, blank=True, null=True)
    added_by = models.CharField(max_length=255, blank=True, null=True)
    if_available = models.CharField(max_length=255, blank=True, null=True)
    tid_pin = models.CharField(max_length=255, blank=True, null=True)
    physical_address = models.CharField(max_length=255, blank=True, null=True)
    merchant_cat_code = models.CharField(max_length=255, blank=True, null=True)
    ptsp = models.CharField(max_length=255, blank=True, null=True)
    mechant_account_name = models.CharField(max_length=255, blank=True, null=True)
    bank_code = models.CharField(max_length=255, blank=True, null=True)
    name_created = models.CharField(max_length=255, blank=True, null=True)
    date_modified = models.CharField(max_length=255, blank=True, null=True)
    name_modified = models.CharField(max_length=255, blank=True, null=True)
    email_alerts = models.CharField(max_length=255, blank=True, null=True)
    visa_acquirer_id_number = models.CharField(max_length=255, blank=True, null=True)
    master_card_acquirer_id_number = models.CharField(max_length=255, blank=True, null=True)
    verve_acquirer_id_number = models.CharField(max_length=255, blank=True, null=True)
    account_name = models.CharField(max_length=255, blank=True, null=True)
    terminal_type = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    country_code = models.CharField(max_length=255, blank=True, null=True)
    payattitude_acquirer_id_number = models.CharField(max_length=255, blank=True, null=True)
    cup_acquirer_id_number = models.CharField(max_length=255, blank=True, null=True)
    jcb_acquirer_id_number = models.CharField(max_length=255, blank=True, null=True)
    maker = models.CharField(max_length=255, blank=True, null=True)
    checker = models.CharField(max_length=255, blank=True, null=True)
    bank_name = models.CharField(max_length=255, blank=True, null=True)
    term_ps_name = models.CharField(max_length=255, blank=True, null=True)
    payarenam_id = models.CharField(max_length=255, blank=True, null=True)
    payarena_tid = models.CharField(max_length=255, blank=True, null=True)
    comm_sid = models.CharField(max_length=255, blank=True, null=True)
    timestamp_field = models.DateTimeField(blank=True, null=True)
    terminal_model_code = models.CharField(max_length=255, blank=True, null=True)
    pan = models.CharField(max_length=255, blank=True, null=True)
    proc_code = models.CharField(max_length=255, blank=True, null=True)
    rrn = models.CharField(max_length=255, blank=True, null=True)
    stan = models.CharField(max_length=255, blank=True, null=True)
    message_date = models.DateTimeField(blank=True, null=True)
    message_started_date = models.DateTimeField(blank=True, null=True)
    resp_code = models.CharField(max_length=255, blank=True, null=True)
    auth_code = models.CharField(max_length=255, blank=True, null=True)
    message_date_completed = models.DateTimeField(blank=True, null=True)
    amount = models.FloatField(blank=True, null=True)
    currency = models.CharField(max_length=255, blank=True, null=True)
    source = models.CharField(max_length=255, blank=True, null=True)
    destination = models.CharField(max_length=255, blank=True, null=True)
    hostrespcode = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'up_con_terminal_config'


class UpDms(models.Model):
    trans_date = models.DateTimeField(blank=True, null=True)
    settlement_date = models.DateTimeField(blank=True, null=True)
    dispute_date = models.DateTimeField(blank=True, null=True)
    due_date = models.DateTimeField(blank=True, null=True)
    reversal_date = models.DateTimeField(blank=True, null=True)
    reversal_settlement_date = models.DateTimeField(blank=True, null=True)
    cpd = models.DateTimeField(blank=True, null=True)
    dispute_status = models.CharField(max_length=255, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    trans_amount = models.CharField(max_length=255, blank=True, null=True)
    trans_time = models.CharField(max_length=255, blank=True, null=True)
    masked_pan = models.CharField(max_length=255, blank=True, null=True)
    acct_no = models.CharField(max_length=255, blank=True, null=True)
    trans_type = models.CharField(max_length=255, blank=True, null=True)
    response = models.CharField(max_length=255, blank=True, null=True)
    issuer = models.CharField(max_length=255, blank=True, null=True)
    acquirer = models.CharField(max_length=255, blank=True, null=True)
    issuer_stan = models.CharField(max_length=255, blank=True, null=True)
    acquirer_stan = models.CharField(max_length=255, blank=True, null=True)
    acquirer_rrn = models.CharField(max_length=255, blank=True, null=True)
    issuer_rrn = models.CharField(max_length=255, blank=True, null=True)
    order_id = models.CharField(max_length=255, blank=True, null=True)
    dispense_amount = models.CharField(max_length=255, blank=True, null=True)
    log_comment = models.CharField(max_length=255, blank=True, null=True)
    full_access = models.CharField(max_length=255, blank=True, null=True)
    reversal_id = models.CharField(max_length=255, blank=True, null=True)
    reversal_amount = models.CharField(max_length=255, blank=True, null=True)
    channel = models.CharField(max_length=255, blank=True, null=True)
    trans_fee = models.CharField(max_length=255, blank=True, null=True)
    merchant_name = models.CharField(max_length=255, blank=True, null=True)
    merchant_id = models.CharField(max_length=255, blank=True, null=True)
    orig_terminal_id = models.CharField(max_length=255, blank=True, null=True)
    fee_in_original_amt = models.CharField(max_length=255, blank=True, null=True)
    credit_val = models.CharField(max_length=255, blank=True, null=True)
    orig_merchant_name = models.CharField(max_length=255, blank=True, null=True)
    text_mess = models.CharField(max_length=255, blank=True, null=True)
    agent_acct = models.CharField(max_length=255, blank=True, null=True)
    scheme_log_code = models.CharField(max_length=255, blank=True, null=True)
    source_bank = models.CharField(max_length=255, blank=True, null=True)
    dest_bank = models.CharField(max_length=255, blank=True, null=True)
    status_code = models.CharField(max_length=255, blank=True, null=True)
    debit_account = models.CharField(max_length=255, blank=True, null=True)
    trf_rrn = models.CharField(max_length=255, blank=True, null=True)
    department_table_id = models.CharField(max_length=255, blank=True, null=True)
    department = models.CharField(max_length=255, blank=True, null=True)
    schema_or_table_name = models.CharField(max_length=255, blank=True, null=True)
    terminal_id = models.CharField(max_length=255, blank=True, null=True)
    trans_id = models.CharField(max_length=255, blank=True, null=True)
    dispute_id = models.CharField(max_length=255, blank=True, null=True)
    approval_code = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'up_dms'
