# Generated by Django 4.2.6 on 2024-05-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_bespoke'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bespoke',
        ),
    ]
