# Generated by Django 4.2.6 on 2024-04-13 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days_to_run', models.IntegerField(default=1, help_text='Number of days to run; Default 1 day; which means insight runs every 1 day')),
                ('daily_count_days', models.IntegerField(blank=True, default=7, help_text='The total count of days used for running the analysis.', null=True)),
                ('weekly_count_days', models.IntegerField(blank=True, default=4, help_text='The total count of week used for running the analysis.', null=True)),
                ('monthly_count_days', models.IntegerField(blank=True, default=3, help_text='The total count of month used for running the analysis.', null=True)),
                ('time_of_day_to_run', models.TimeField(default=datetime.time(4, 0), help_text='Time of the day for the insight process to run')),
            ],
        ),
        migrations.CreateModel(
            name='InsightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('admin_activated', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InsightConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('daily_threshold_up', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('daily_threshold_down', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('daily_bench_mark', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True)),
                ('daily_bench_mark_with_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True)),
                ('weekly_threshold_up', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('weekly_threshold_down', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('weekly_bench_mark', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True)),
                ('weekly_bench_mark_with_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True)),
                ('monthly_threshold_up', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('monthly_threshold_down', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('priority', models.CharField(choices=[('Urgent', 'urgent'), ('Important', 'important'), ('Critical', 'critical'), ('Info', 'info')], default='Info', max_length=25)),
                ('monthly_bench_mark', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True)),
                ('monthly_bench_mark_with_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text="Incase 'institution' wants to manually spool insight analysis from start date to end date.start date: 2021-02-20 to end date: 2024-02-29", null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text="Incase 'institution' wants to spool insight analysis from start date to end date. start date: 2021-02-20 to end date: 2024-02-29", null=True)),
                ('short_message', models.TextField(help_text='Notification header; This can be edited by the owner of the insight.', null=True)),
                ('long_message', models.TextField(help_text='Notification body; This carried detail of analysis; This can be edited by the owner of the insight.', null=True)),
                ('recommendation', models.TextField(help_text='Recommendation after analysis; To be added to long message; This can be edited by the owner of the insight.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('result', models.JSONField(default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date when this instance was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date when this instance was updated.')),
                ('insight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insight_module.insightmodel')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InsightAnalysisNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('priority', models.CharField(choices=[('Urgent', 'urgent'), ('Important', 'important'), ('Critical', 'critical'), ('Info', 'info')], default='Info', max_length=25)),
                ('start_time', models.DateTimeField(help_text='Incase user wants to spool insight analysis fromstart date to end date.start date: 2021-02-20 to end date: 2024-02-29', null=True)),
                ('end_time', models.DateTimeField(help_text='Incase user wants to spool insight analysis from start date to end date. start date: 2021-02-20 to end date: 2024-02-29', null=True)),
                ('short_message', models.TextField(help_text="A copy; Short Message that was set in the 'InsightConfigModel' instance;Notification header; This can only be edited in the 'InsightConfigModel';", null=True)),
                ('long_message', models.TextField(help_text="A copy; Long Detailed Message that was set in the 'InsightConfigModel' instance; Notification body; This carried detail of analysis; This can only be edited in the 'InsightConfigModel';", null=True)),
                ('read', models.BooleanField(default=False, help_text='`False` if user has not clicked to view this notification; `True` if user has clicked to view this notification;')),
                ('recommendation', models.TextField(help_text="A copy; Recommendation that was set in the 'InsightConfigModel' instance after analysis; To be added to long message; This can be edited by the owner of the insight.", null=True)),
                ('result', models.JSONField(default=dict, help_text="A copy of the 'InsightConfigModel' `result`")),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('insight_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insight_module.insightconfigmodel')),
            ],
        ),
    ]
