# Generated by Django 4.2.6 on 2024-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightanalysisnotificationmodel',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('critical', 'Critical'), ('info', 'Info')], default='Info', max_length=25),
        ),
        migrations.AlterField(
            model_name='insightconfigmodel',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('critical', 'Critical'), ('info', 'Info')], default='Info', max_length=25),
        ),
    ]
