# Generated by Django 4.2.6 on 2024-05-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_module', '0002_alter_insightanalysisnotificationmodel_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightconfigmodel',
            name='insight_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='insightanalysisnotificationmodel',
            name='priority',
            field=models.CharField(choices=[(1, 'Urgent'), (2, 'Important'), (3, 'Critical'), (4, 'Info')], default='Info', max_length=25),
        ),
        migrations.AlterField(
            model_name='insightconfigmodel',
            name='priority',
            field=models.CharField(choices=[(1, 'Urgent'), (2, 'Important'), (3, 'Critical'), (4, 'Info')], default='Info', max_length=25),
        ),
    ]
