ENVIRON=production
DATA_WAREHOUSE_DB_NAME=bi_application
DATA_WAREHOUSE_DB_USER=postgres

DATA_WAREHOUSE_DB_PSWD=dt8UkT6OINR4p0D4
DATA_WAREHOUSE_DB_HOST=192.168.40.33
DATA_WAREHOUSE_DB_PORT=4019
DATA_WAREHOUSE_DB_SCHEMA=etl_schema
DATA_WAREHOUSE_RECORD_TABLE=process_record

# SPARK SPECIFIC VARIABLES
SPARK_DRIVER_EXTRA_CLASS_PATHS=/home/saccount/etl-process/etl_layer/db_drivers/ojdbc11.jar:/home/saccount/etl-process/etl_layer/db_drivers/postgresql-42.5.3.jar
SPARK_JARS_PATHS=/home/saccount/etl-process/etl_layer/db_drivers/ojdbc11.jar,/home/saccount/etl-process/etl_layer/db_drivers/postgresql-42.5.3.jar
MAX_TO_STRING_FIELDS=2000000


# =========== PROCESSING DEPARTMENT DETAILS ==========
PROCESSING_DATA_SOURCE_READ_FROM_TABLE_NAME=TLA
PROCESSING_DATA_SOURCE_DB_NAME=TWODB.UPDC1.COM
PROCESSING_DATA_SOURCE_DB_TYPE=oracle
PROCESSING_DATA_SOURCE_SCHEMA=BAOBAB
PROCESSING_DATA_SOURCE_DB_USER=BI
PROCESSING_DATA_SOURCE_DB_PASSWORD=BIbi@1234
PROCESSING_DATA_SOURCE_DB_PORT=1800
PROCESSING_DATA_SOURCE_DB_HOST=172.19.104.22
PROCESSING_DATA_SOURCE_DB_DRIVER=oracle.jdbc.OracleDriver
PROCESSING_DATA_WAREHOUSE_WRITE_TO_TABLE_NAME=transactions
PROCESSING_DATA_WAREHOUSE_SCHEMA=etl_schema


# ========== BANK BRANCH DETAILS ==========
BANK_BRANCH_DATA_SOURCE_NAME=postgres
BANK_BRANCH_DATA_SOURCE_PSWD=vnp-1234
BANK_BRANCH_DATA_SOURCE_HOST=172.19.8.161
BANK_BRANCH_DATA_SOURCE_PORT=1700
BANK_BRANCH_DATA_SOURCE_DB_NAME=bannkbranch
BANK_BRANCH_DATA_SOURCE_READ_FROM_SCHEMA=public
BANK_BRANCH_DATA_SOURCE_READ_FROM_TABLE_NAME=paycol_transaction_tab
BANK_BRANCH_DATA_WAREHOUSE_WRITE_TO_TABLE_NAME=bank_branch_etl


# =========== BESPOKE =============
BESPOKE_DATA_WAREHOUSE_SCHEMA=etl_schema
BESPOKE_DATA_WAREHOUSE_WRITE_TO_TABLE_NAME=transactions
BESPOKE_DATA_SOURCE_DATABASE_TYPE=postgresql
BESPOKE_DATA_SOURCE_DATABASE_HOST=172.19.4.119
BESPOKE_DATA_SOURCE_DATABASE_PORT=1701
BESPOKE_DATA_SOURCE_DATABASE_TABLE_NAME=patdb
BESPOKE_DATA_SOURCE_DATABASE_USER=bi
BESPOKE_DATA_SOURCE_DATABASE_PSWD=B3sp0k$-1234
BESPOKE_DATA_SOURCE_DRIVER=org.postgresql.Driver
BESPOKE_DATA_SOURCE_SCHEMA=switch
BESPOKE_DATA_SOURCE_TABLE=transactions

# ========= HOLDER BESPOKE ========
HOLDER_BESPOKE_DATA_SOURCE_SCHEMA=switch
HOLDER_BESPOKE_DATA_SOURCE_DATABASE_TABLE=holders
HOLDER_BESPOKE_DATA_SOURCE_DATABASE_HOST=172.19.4.119
HOLDER_BESPOKE_DATA_SOURCE_DATABASE_PORT=1701
HOLDER_BESPOKE_DATA_SOURCE_DATABASE_NAME=patdb
HOLDER_BESPOKE_DATA_SOURCE_DATABASE_USER=bi
HOLDER_BESPOKE_DATA_SOURCE_DATABASE_PSWD=B3sp0k$-1234
HOLDER_BESPOKE_DATA_SOURCE_DATABASE_DRIVER=org.postgresql.Driver
HOLDER_BESPOKE_DATA_WAREHOUSE_DATABASE_SCHEMA=etl_schema
HOLDER_BESPOKE_DATA_WAREHOUSE_DATABASE_TABLE=holdertags


# ======== ISSUING TACCOUNT =========
ISSUING_TACCOUNT_DATA_SOURCE_DATABASE_TYPE=oracle
ISSUING_TACCOUNT_DATA_SOURCE_DATABASE_HOST=172.19.4.150
ISSUING_TACCOUNT_DATA_SOURCE_DATABASE_PORT=1700
ISSUING_TACCOUNT_DATA_SOURCE_DATABASE_NAME=TWCMS_STY
ISSUING_TACCOUNT_DATA_SOURCE_DATABASE_USER=BI
ISSUING_TACCOUNT_DATA_SOURCE_DATABASE_SCHEMA=a4m
ISSUING_TACCOUNT_DATA_SOURCE_DATABASE_TABLE_NAME=taccount
ISSUING_TACCOUNT_DATA_SOURCE_DATABASE_PSWD=BIbi$$-1234
ISSUING_TACCOUNT_DATA_SOURCE_DATABASE_DRIVER=oracle.jdbc.OracleDriver
ISSUING_TACCOUNT_DATA_WARE_HOUSE_DATABASE_TABLE=card_account_details_issuing


# ============ ISSUING TCARD =============
ISSUING_TCARD_DATA_SOURCE_DATABASE_SCHEMA=a4m
ISSUING_TCARD_DATA_SOURCE_DATABASE_TABLE=tcard
ISSUING_TCARD_DATA_SOURCE_DATABASE_TYPE=oracle
ISSUING_TCARD_DATA_SOURCE_DATABASE_HOST=172.19.8.229
ISSUING_TCARD_DATA_SOURCE_DATABASE_PORT=1700
ISSUING_TCARD_DATA_SOURCE_DATABASE_NAME=a4mtest
ISSUING_TCARD_DATA_SOURCE_DATABASE_USER=a4m
ISSUING_TCARD_DATA_SOURCE_DATABASE_PASSWORD=a4m
ISSUING_TCARD_DATA_SOURCE_DATABASE_DRIVER=oracle.jdbc.OracleDriver
ISSUING_TCARD_DATA_WAREHOUSE_DATABASE_TABLE=card_account_details_issuing


# ===========ISSUING TCLIENT ============
ISSUING_TCLIENT_DATA_SOURCE_DATABASE_SCHEMA=a4m
ISSUING_TCLIENT_DATA_SOURCE_DATABASE_TABLE=tclientpersone
ISSUING_TCLIENT_DATA_SOURCE_DATABASE_TYPE=oracle
ISSUING_TCLIENT_DATA_SOURCE_DATABASE_HOST=172.19.8.229
ISSUING_TCLIENT_DATA_SOURCE_DATABASE_PORT=1700
ISSUING_TCLIENT_DATA_SOURCE_DATABASE_NAME=a4mtest
ISSUING_TCLIENT_DATA_SOURCE_DATABASE_USER=a4m
ISSUING_TCLIENT_DATA_SOURCE_DATABASE_PASSWORD=a4m
ISSUING_TCLIENT_DATA_SOURCE_DATABASE_DRIVER=oracle.jdbc.OracleDriver
ISSUING_TCLIENT_DATA_WAREHOUSE_DATABASE_TABLE=card_client_personnel_issuing



# ======== PAYARENA EXCHANGE =========
PAYARENA_DATA_SOURCE_DATABASE_USER=bi
PAYARENA_DATA_SOURCE_DATABASE_PASSWORD=B!P0rtAl
PAYARENA_DATA_SOURCE_DATABASE_HOST=172.19.6.17
PAYARENA_DATA_SOURCE_DATABASE_PORT=1700
PAYARENA_DATA_SOURCE_DATABASE_NAME=payarenav2

PAYARENA_DATA_WARE_HOUSE_DATABASE_TABLE=payarena_exchange
#PAYARENA_DATA_WARE_HOUSE_DATABASE_SCHEMA=switch
PAYARENA_DATA_SOURCE_READ_FROM_TABLE=transfers
PAYARENA_DATA_SOURCE_DATABASE_SCHEMA=switch

# ======= SETTLEMENT DETAILS ======
SETTLEMENT_DETAIL_DATA_SOURCE_DATABASE_SCHEMA=DPPADMIN
SETTLEMENT_DETAIL_DATA_SOURCE_DATABASE_TABLE=POSMISDB_SETTLEMENTDETAIL_BKP
SETTLEMENT_DETAIL_DATA_SOURCE_DATABASE_USER=bi
SETTLEMENT_DETAIL_DATA_SOURCE_DATABASE_PASSWORD=vnp$1234
SETTLEMENT_DETAIL_DATA_SOURCE_DATABASE_HOST=172.19.104.17
SETTLEMENT_DETAIL_DATA_SOURCE_DATABASE_PORT=1800
SETTLEMENT_DETAIL_DATA_SOURCE_DATABASE_NAME=Unisetdb.updc1.com
SETTLEMENT_DETAIL_DATA_WARE_HOUSE_DATABASE_TABLE=settlement_detail


# ============ TAG BESPOKE ==========
TAG_BESPOKE_DATA_SOURCE_DATABASE_SCHEMA=switch
TAG_BESPOKE_DATA_SOURCE_DATABASE_TABLE=tags
TAG_BESPOKE_DATA_SOURCE_DATABASE_HOST=172.19.4.119
TAG_BESPOKE_DATA_SOURCE_DATABASE_PORT=1701
TAG_BESPOKE_DATA_SOURCE_DATABASE_NAME=patdb
TAG_BESPOKE_DATA_SOURCE_DATABASE_USER=bi
TAG_BESPOKE_DATA_SOURCE_DATABASE_PASSWORD=B3sp0k$-1234
TAG_BESPOKE_DATA_SOURCE_DATABASE_DRIVER=org.postgresql.Driver
TAG_BESPOKE_DATA_WARE_HOUSE_DATABASE_SCHEMA=etl_schema
TAG_BESPOKE_DATA_WARE_HOUSE_DATABASE_TABLE=holdertags


# ========= TERMINAL CONFIG (UP CONNECT) =========
TERMINAL_CONFIG_DATA_SOURCE_DATABASE_HOST=172.19.6.58
TERMINAL_CONFIG_DATA_SOURCE_DATABASE_SCHEMA=tcm
TERMINAL_CONFIG_DATA_SOURCE_READ_FROM_TABLE=terminalconfiguration
TERMINAL_CONFIG_DATA_SOURCE_DATABASE_PORT=1700
TERMINAL_CONFIG_DATA_SOURCE_DATABASE_NAME=tcmdb
TERMINAL_CONFIG_DATA_SOURCE_DATABASE_USER=bi
TERMINAL_CONFIG_DATA_SOURCE_DATABASE_TABLE=terminalconfiguration
TERMINAL_CONFIG_DATA_SOURCE_DATABASE_PASSWORD=B!P0rtAl
TERMINAL_CONFIG_DATA_SOURCE_DATABASE_DRIVER=org.postgresql.Driver
TERMINAL_CONFIG_DATA_WAREHOUSE_DATABASE_DRIVER=org.postgresql.Driver
TERMINAL_CONFIG_DATA_WAREHOUSE_DATABASE_DRIVER_LOCATION=/home/saccount/etl-process/etl_layer/db_drivers/postgresql-42.5.3.jar
TERMINAL_CONFIG_DATA_WARE_HOUSE_DATABASE_SCHEMA=etl_schema
TERMINAL_CONFIG_DATA_WARE_HOUSE_DATABASE_TABLE=up_con_terminal_config



# ========== TERMINAL MESSAGE (UP CONNECT) ==========
TERMINAL_MESSAGE_DATA_SOURCE_DATABASE_HOST=172.19.6.58
TERMINAL_MESSAGE_DATA_SOURCE_DATABASE_SCHEMA=tms
TERMINAL_MESSAGE_DATA_SOURCE_READ_FROM_TABLE=messages
TERMINAL_MESSAGE_DATA_SOURCE_DATABASE_PORT=1700
TERMINAL_MESSAGE_DATA_SOURCE_DATABASE_NAME=tcmdb
TERMINAL_MESSAGE_DATA_SOURCE_DATABASE_USER=bi
TERMINAL_MESSAGE_DATA_SOURCE_DATABASE_TABLE=terminalconfiguration
TERMINAL_MESSAGE_DATA_SOURCE_DATABASE_PASSWORD=B!P0rtAl
TERMINAL_MESSAGE_DATA_SOURCE_DATABASE_DRIVER=org.postgresql.Driver
TERMINAL_MESSAGE_DATA_WAREHOUSE_DATABASE_DRIVER=org.postgresql.Driver
TERMINAL_MESSAGE_DATA_WAREHOUSE_DATABASE_DRIVER_LOCATION=/home/saccount/etl-process/etl_layer/db_drivers/postgresql-42.5.3.jar
TERMINAL_MESSAGE_DATA_WARE_HOUSE_DATABASE_SCHEMA=etl_schema
TERMINAL_MESSAGE_DATA_WARE_HOUSE_DATABASE_TABLE=up_con_terminal_config


# ========== UP DMS ===========
UP_DMS_DATA_SOURCE_DATABASE_HOST=172.19.8.29
UP_DMS_DATA_SOURCE_DATABASE_USER=upsl_bi
UP_DMS_DATA_SOURCE_DATABASE_PASSWORD=vnp-1234
UP_DMS_DATA_SOURCE_DATABASE_PORT=5434
UP_DMS_DATA_SOURCE_DATABASE_NAME=dmstest
UP_DMS_DATA_SOURCE_DATABASE_SCHEMA=dbo
UP_DMS_DATA_SOURCE_DATABASE_TABLE=disputetransaction

UP_DMS_DATA_WARE_HOUSE_DATABASE_SCHEMA=etl_schema
UP_DMS_DATA_WARE_HOUSE_DATABASE_TABLE=up_dms



# ======= SETTLEMENT MEB ======
SETTLEMENT_MEB_DATA_SOURCE_DATABASE_SCHEMA=dppadmin
SETTLEMENT_MEB_DATA_SOURCE_DATABASE_TABLE=POSMISDB_MEB
SETTLEMENT_MEB_DATA_SOURCE_DATABASE_USER=BI
SETTLEMENT_MEB_DATA_SOURCE_DATABASE_PASSWORD=vnp$1234
SETTLEMENT_MEB_DATA_SOURCE_DATABASE_HOST=172.19.104.17
SETTLEMENT_MEB_DATA_SOURCE_DATABASE_PORT=1800
SETTLEMENT_MEB_DATA_SOURCE_DATABASE_NAME=Unisetdb.updc1.com
SETTLEMENT_MEB_DATA_WARE_HOUSE_DATABASE_TABLE=settlement_meb



# ======== TRANSACTION TYPE SCRIPT VARIABLES ========
# This script carries an excel sheet which contains the transaction type, in which the data are taken from the sheet
# and are written to a DATABASE in the data warehouse.
PATH_TO_EXCEL_SHEET=/home/saccount/etl_layer/load_trans_types.xlsx
DATA_WARE_HOUSE_WRITE_TO_TABLE=transaction_type



# START READING FROM last x days ago.
START_FROM_THESE_DAYS_AGO=10

# STOP AT x days BEFORE TODAY.
END_AT_THIS_DAY_COUNT=1


